/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgainstSeat } from './againstSeat';


export interface AgainstGame { 
    seats: Array<AgainstSeat>;
    batchNr: number;
    categoryNr: number;
    pouleNr: number;
    sportNr: number;
    fieldNr: number;
}

