/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeatEnum } from './seatEnum';


export interface AgainstSeat { 
    seatEnum: SeatEnum;
    seatNr: number;
}
export namespace AgainstSeat {
}


