/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Poule } from './poule';


export interface Category { 
    categoryNr: number;
    poules: Array<Poule>;
}

