/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldPouleFiltersInner } from './fieldPouleFiltersInner';


export interface Field { 
    fieldNr: number;
    /**
     * All poules will be used when: - If no pouleFilters - If no pouleNrs available When pouleFilters are active all poules should be covered 
     */
    pouleFilters: Array<FieldPouleFiltersInner>;
}

