/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GamesDefaultOrderEnum = {
    CycleFirst: 'CycleFirst',
    PouleFirst: 'PouleFirst'
} as const;
export type GamesDefaultOrderEnum = typeof GamesDefaultOrderEnum[keyof typeof GamesDefaultOrderEnum];

