/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneratePlanning400Response { 
    /**
     * Error message describing the bad request
     */
    message?: string;
}

