/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgainstGame } from './againstGame';
import { TogetherSeat } from './togetherSeat';
import { TogetherGame } from './togetherGame';


export interface PlanningGamesInner { 
    seats: Array<TogetherSeat>;
    batchNr: number;
    categoryNr: number;
    pouleNr: number;
    sportNr: number;
    fieldNr: number;
}

