/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanningConfigurationMaxNrOfGamesInARow } from './planningConfigurationMaxNrOfGamesInARow';
import { Sport } from './sport';
import { Category } from './category';
import { Referee } from './referee';
import { GamesDefaultOrderEnum } from './gamesDefaultOrderEnum';


export interface PlanningConfiguration { 
    categories: Array<Category>;
    sports: Array<Sport>;
    referees: Array<Referee>;
    gameOrder: GamesDefaultOrderEnum;
    maxNrOfGamesInARow?: PlanningConfigurationMaxNrOfGamesInARow | null;
}
export namespace PlanningConfiguration {
}


