/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanningConfiguration } from './planningConfiguration';
import { PlanningGamesInner } from './planningGamesInner';


export interface Planning { 
    planningConfiguration: PlanningConfiguration;
    games: Array<PlanningGamesInner>;
}

