/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Poule { 
    pouleNr: number;
    /**
     * The maximum difference between the greatest and smallest poule is always 1 
     */
    places: Array<number>;
}

