/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefereeFiltersInner } from './refereeFiltersInner';


export interface Referee { 
    refereeNr: number;
    /**
     * All poules will be used when: - If no pouleFilters - If no pouleNrs available When pouleFilters are active all poules should be covered 
     */
    filters: Array<RefereeFiltersInner>;
}

