/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SeatEnum = {
    HomeSeat: 'HomeSeat',
    AwaySeat: 'AwaySeat',
    NorthSeat: 'NorthSeat',
    SouthSeat: 'SouthSeat',
    WestSeat: 'WestSeat',
    EastSeat: 'EastSeat'
} as const;
export type SeatEnum = typeof SeatEnum[keyof typeof SeatEnum];

