/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SelfRefereeEnum = {
    SamePoule: 'SamePoule',
    OtherPoules: 'OtherPoules'
} as const;
export type SelfRefereeEnum = typeof SelfRefereeEnum[keyof typeof SelfRefereeEnum];

