/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SelfRefereeEnum } from './selfRefereeEnum';


export interface SportSelfRefereeInfo { 
    selfReferee: SelfRefereeEnum;
    nrOfSeatsPerGame: number;
}
export namespace SportSelfRefereeInfo {
}


