/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Field } from './field';
import { SportSelfRefereeInfo } from './sportSelfRefereeInfo';
import { SeatEnum } from './seatEnum';


export interface Sport { 
    sportNr: number;
    nrOfCycles: number;
    seatEnum: SeatEnum;
    nrOfRefereesPerGame: number;
    fields: Array<Field>;
    selfRefereeInfo?: SportSelfRefereeInfo | null;
}
export namespace Sport {
}


