/**
 * Sports Planning API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TogetherSeat } from './togetherSeat';


export interface TogetherGame { 
    seats?: Array<TogetherSeat>;
    categoryNr: number;
    pouleNr: number;
    sportNr: number;
    fieldNr: number;
}

