name: Release Actions
on: 
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:     
      # - uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{secrets.SSH_TOKEN}}
      #     # name: id_rsa # optional
      #     known_hosts: ${{secrets.KNOWN_HOSTS}}
          # config: #{{ secrets.CONFIG }} # ssh_config; optional
          # if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci && npm run build && npm run test
      - run: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN}}
          GITHUB_TOKEN: ${{secrets.REPOS_GITHUB_ACCESS_TOKEN}}